### ISSUE TITLE
issue with private test environment

### ISSUE THREAD

**Issue by naragonn** [JackKBroome/Dot_BOTC#3]
https://github.com/JackKBroome/Dot_BOTC/blob/e10dda0230e662fd73e13ed8615d6302db71533b/Dot%203%20Github.py#L10-L11

I am getting the error:

`'Intents' object attribute 'message_content' is read-only` 

What version of nextcord is used?
can you include a .env and requirements.txt

don`t forget to remove the bot token from .env

**Comment by jeremyroman** [comment]
#4 might address these concerns
